import { Room } from "@/model/room";
import { particpants } from "./paricipant-data";
import { VOTING_SYSTEM } from "@/model/user";

export const room1: Room = {
  id: 1,
  name: "Room 1",
  capacity: 10,
  createdAt: new Date().toISOString(),
  owner: particpants[0],
  publicKey: "1",
  votingSystem: VOTING_SYSTEM.FIBONACCI,
  currentPlayersCount: 0,
  participants: [],
};

export const rooms: Room[] = [
  {
    id: 1,
    name: "Room 1",
    capacity: 10,
    createdAt: new Date().toISOString(),
    owner: particpants[0],
    publicKey: "1",
    votingSystem: VOTING_SYSTEM.FIBONACCI,
    currentPlayersCount: 0,
    participants: [],
  },
  {
    id: 2,
    name: "Room 2",
    capacity: 8,
    createdAt: new Date().toISOString(),
    owner: particpants[6],
    publicKey: "2",
    votingSystem: VOTING_SYSTEM.TSHIRT,
    currentPlayersCount: 2,
    participants: [particpants[6], particpants[7]],
  },
  {
    id: 3,
    name: "Room 3",
    capacity: 5,
    createdAt: new Date().toISOString(),
    owner: particpants[11],
    publicKey: "3",
    votingSystem: VOTING_SYSTEM.FIBONACCI,
    currentPlayersCount: 5,
    participants: [
      particpants[11],
      particpants[10],
      particpants[9],
      particpants[8],
      particpants[7],
    ],
  },
  {
    id: 4,
    name: "Room 4",
    capacity: 7,
    createdAt: new Date().toISOString(),
    owner: particpants[7],
    publicKey: "4",
    votingSystem: VOTING_SYSTEM.TSHIRT,
    currentPlayersCount: 3,
    participants: [particpants[7], particpants[8], particpants[9]],
  },
  {
    id: 5,
    name: "Room 5",
    capacity: 8,
    createdAt: new Date().toISOString(),
    owner: particpants[5],
    publicKey: "5",
    votingSystem: VOTING_SYSTEM.FIBONACCI,
    currentPlayersCount: 1,
    participants: [particpants[5]],
  },
  {
    id: 6,
    name: "Room 6",
    capacity: 10,
    createdAt: new Date().toISOString(),
    owner: particpants[3],
    publicKey: "6",
    votingSystem: VOTING_SYSTEM.TSHIRT,
    currentPlayersCount: 4,
    participants: [
      particpants[3],
      particpants[4],
      particpants[5],
      particpants[6],
    ],
  },
  {
    id: 7,
    name: "Room 7",
    capacity: 5,
    createdAt: new Date().toISOString(),
    owner: particpants[9],
    publicKey: "7",
    votingSystem: VOTING_SYSTEM.FIBONACCI,
    currentPlayersCount: 2,
    participants: [particpants[9], particpants[10]],
  },
];
